### ISSUE TITLE
Can this be used for an offline Flutter app?

### ISSUE THREAD

**Issue by BradyEdgar94** [medz/prisma-dart#118]
I am looking to convert my Flutter app to be offline first, which means migrating from my GraphQL API(using Prisma) to a local DB Flutter solution. This Prisma-Dart package would be perfect for me if it means a user can have their own DB records stored on their phone. So I am trying to see if that is possible with this package.

My requirements are to have a persistant local DB and handle CRUD operations using this prisma-dart package.

Is this something that is possible with this package?

Thanks so much!

**Comment by medz** [comment]
This is in the support plan. I am in the official Prisma discussion group. It is expected that the dynamic library support will be standardized in the future, then this function will become a reality.

**Comment by SpongeManiac** [comment]
It would be very helpful if this was _explicitly_ mentioned as a limitation to this package. I have spent the last week developing around this because I thought it was a complete port of the JavaScript Prisma, allowing for local databases, but as I have just found out the hard way, this is _**not**_ implemented. Here is the error I received before looking this up:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PrismaInitializationException: Cannot find the query engine binary (Basename: D:\GitHub\flutter-ws-test\node_modules\prisma\query-engine-windows.exe)
E/flutter (10903): #0      BinaryEngine.resolvedExecutable (package:orm/binary_engine.dart:79:5)
E/flutter (10903): #1      BinaryEngine._createProcess (package:orm/binary_engine.dart:178:7)
E/flutter (10903): #2      BinaryEngine.start (package:orm/binary_engine.dart:148:23)
E/flutter (10903): <asynchronous suspension>
E/flutter (10903): #3      UniversalEngine.request (package:orm/universal_engine.dart:59:5)
E/flutter (10903): <asynchronous suspension>
E/flutter (10903): #4      ModelDelegate._execute (package:orm/src/client/model_delegate.dart:40:20)
E/flutter (10903): <asynchronous suspension>
E/flutter (10903): #5      PrismaFluent.queryBuilder.<anonymous closure> (package:orm/src/client/prisma_fluent.dart:37:22)
E/flutter (10903): <asynchronous suspension>
E/flutter (10903): #6      PrismaFluent.queryBuilder.<anonymous closure> (package:orm/src/client/prisma_fluent.dart:37:22)
E/flutter (10903): <asynchronous suspension>
E/flutter (10903): #7      PrismaFluent.queryBuilder.<anonymous closure> (package:orm/src/client/prisma_fluent.dart:37:22)
E/flutter (10903): <asynchronous suspension>
E/flutter (10903): #8      PrismaProvider.preferencesExists (package:flutter_ws/platform/io/prisma/prisma_provider.dart:74:12)
E/flutter (10903): <asynchronous suspension>
E/flutter (10903): #9      PrismaProvider.ensurePreferences (package:flutter_ws/platform/io/prisma/prisma_provider.dart:78:10)
E/flutter (10903): <asynchronous suspension>
E/flutter (10903): #10     PrismaProvider.init (package:flutter_ws/platform/io/prisma/prisma_provider.dart:109:5)
E/flutter (10903): <asynchronous suspension>
E/flutter (10903): #11     AppImpl.main (package:flutter_ws/platform/io/platform_io.dart:114:5)
E/flutter (10903): <asynchronous suspension>
E/flutter (10903): #12     PlatformApp.startApp (package:flutter_ws/platform_app.dart:12:5)
E/flutter (10903): <asynchronous suspension>
E/flutter (10903): #13     main (package:flutter_ws/main.dart:7:3)
E/flutter (10903): <asynchronous suspension>
```

I'm still looking for a decent ORM for local databases. I'll be switching to [Drift](https://pub.dev/packages/drift) in the mean time.

**Comment by medz** [comment]
@BradyEdgar94 @SpongeManiac 
Currently Flutter only supports Data Proxy, please use `--data-proxy` when generating the client
Docs: `npx prisma generate --data-proxy` -> https://www.prisma.io/docs/data-platform/about

Unfortunately, Library has not been developed yet because I am new to Rust.

**Comment by medz** [comment]
<img width="814" alt="image" src="https://github.com/odroe/prisma-dart/assets/5564821/dc2ad1bd-711e-44c6-bdd9-9953cee519c2">

**Comment by MulverineX** [comment]
I was curious what the current status of this is? The Engine Binary being supported on Flutter Native, that is. Is there any documentation or prior examples of this being done in other languages? I'd love to help.

**Comment by medz** [comment]
> I was curious what the current status of this is? The Engine Binary being supported on Flutter Native, that is. Is there any documentation or prior examples of this being done in other languages? I'd love to help.

Flutter does not support binary engine files, and Prisma engines https://github.com/prisma/prisma-engines are not ready to be built for CAPI. In other words, if I want to provide an offline local database for Prisma Support, I have to write a CAPI engine whose output target is a dynamic library (so/dll), which is cumbersome, but I'm working on it, I'm building the new Prisma client API, and when it's finished, I can start building the engine part .

**Comment by medz** [comment]
One reason, as mentioned above, is that I am new to Rust. This was a big challenge for me, as I needed to learn the Rust language and develop it at the same time.

**Comment by MulverineX** [comment]
I'm actually doing a similar thing with Mercury, I've never worked with C++ before, but I had to for the project. I wouldn't mind having to do that again for this project, I'd love to know how/if I could help!

**Comment by listepo** [comment]
https://pub.dev/packages/flutter_rust_bridge maybe can help

**Comment by medz** [comment]
> https://pub.dev/packages/flutter_rust_bridge maybe can help

After I communicated with the Prisma Team, they have started working on the experimental C ABI engine 👉 https://github.com/prisma/prisma-engines/tree/osp/rn/query-engine/query-engine-rn They have already made it Added to this quarter’s roadmap!

<img width="1024" alt="image" src="https://github.com/medz/prisma-dart/assets/5564821/a47250e4-b12e-45ec-873f-f0bc6eab5c38">
Please wait patiently, 4.0 will finally use the C ABI engine officially produced by Prisma, so that it can run in Flutter.

**Comment by medz** [comment]
In addition, I am making a temporary replacement version https://github.com/medz/prisma-dart/tree/main/packages/engine_ffi until the C ABI engine is officially released. Since I am new to Rust, my progress may be slow.

**Comment by medz** [comment]
An alternative is to wait for the Dart team to implement https://github.com/dart-lang/sdk/issues/51383 this feature. At that time, I will make a Dart NAPI compatible program that can run in Dart using the Node API's dylib. However, it is obvious that Prisma Team will implement the C ABI engine faster.

**Comment by medz** [comment]
#328
