### ISSUE TITLE
Cannot launch on another computer.

### ISSUE THREAD

**Issue by PandaGuerrier** [medz/prisma-dart#127]
Hello, I compile my code to send a .exe to my client and my clients cannot launch my application because Prisma create an error..

This is the error:

![image](https://user-images.githubusercontent.com/76222146/221416588-4b1fe9d6-8e5e-4d0a-9576-09c60cfd28ea.png)

**Comment by medz** [comment]
@PandaGuerrier You should re-download the binaries on the target host.

**Comment by medz** [comment]
Alternatively, copy the `node_modules/prisma/query-engine-<platfrom>` file to the directory where the exe is located

**Comment by medz** [comment]
If your version is before 3.0, then you need to copy `.dart_tool/prisma/query-engine` to your exe directory.

**Comment by medz** [comment]
@AndryHTC @PandaGuerrier Maybe we should consider Docker Image, binary causes copying between different systems and architectures will definitely not work.

If I download the engines of all architectures for selection and copying by default, the files you need to send will be extremely large in the end (usually, you can’t determine the target system and architecture before development, you can only send them all)

I recently optimized the `odroe/prisma-dart` Docker image, its goal is to build a thin image that only contains the current dependencies through `scratch`, and I released a new version, the `odroe/prisma-dart` image The size is only 1.5MB, and supports multiple architectures (all architectures supported by Dart Image)

You can refer to this SQLite example https://github.com/odroe/prisma-dart/blob/main/example/Dockerfile

**Comment by medz** [comment]
@AndryHTC I don't have any good method, maybe compiling on the server side is the most direct.

**Comment by AndryHTC** [comment]
@medz running npx prisma generate directly on the EC2 instance isn't a viable solution for us because it causes the server to freeze.

**Comment by medz** [comment]
@AndryHTC What about making a Docker container identical to your EC2? The same system version and the same platform architecture can solve this problem.
