### ISSUE TITLE
Idea: Allow models to be used client side

### ISSUE THREAD

**Issue by blopker** [medz/prisma-dart#166]
This isn't a feature request exactly, but more of opening a discussion. 

Right now, the only reason I'd personally use Dart on the server is code sharing with Flutter. Otherwise, the server-side Dart ecosystem is pretty new compared to other languages and there's currently a distinct disadvantage. In that vein, I'm looking at some classes generated by `prisma-dart` and think they could be useful on the frontend as well.

What if `prisma-dart` generated serializable classes based on the schemas that could be put in a separate package and shared by both the front end and server? Serverpod does this with their own custom YAML-based schema (https://docs.serverpod.dev/concepts/serialization), but it falls pretty short compared to the power of Prisma's schemas, not to mention Prisma's database compatibility.

Some open questions:

- How to have server or frontend only properties on the classes? e.x. Hiding properties, like ID from the frontend.
- How to make the package generation optional for people who don't need it?
- How to generate more generic class other than for example `UserCreateInput` vs just `User`.

If this is possible, it would be pretty easy to make package that turns a standard `shelf` server into a fully type-safe, RPC-like API.

Anyway, happy to close this if it's out of scope, just thought it would be cool!

**Comment by medz** [comment]
I think your proposal is very good 👍

Putting serialized classes into a single Dart in the Prisma client has the following disadvantages:

1. Too much code in the client file
2. It is not conducive to the sharing of serialized models and input and output classes

We need to solve the following problems:

1. On what basis are these classes split?
2. Where is the transformation of the generator implemented?
3. Currently, the output can be specified as the file name in the schema. Will changing it to a directory cause huge troubles for the migration of existing developers?
4. Should there be support for constructing standalone prisma client packages as output? , and at the same time compatible output to directory.
5. How to deal with properties that are only allowed to be exposed in server mode?

> I will stick this issue to the top, so that more people can discover this need for discussion. This suggestion I think is great. Of course, if Dart supports the `Omit` function similar to TS. Question 5 is not a problem.

**Comment by dgaedcke** [comment]
100% agree with this proposal.  I often use the Prisma generated code on the CLIENT SIDE (talking directly to the DB) for prototyping and client demo's, to help them flush out their specs and requirements.   For server code, it makes total sense that all the Model classes are immutable and must be constructed all-at-once (with all fields) from a client API request.  But on the client side, data is collected in pieces, across many screens, and I hate having to manually clone all the Prisma data structures so I have data-models on which to store user-input from the UI!!

Being able to auto-generate "<ModelName>Shadow" classes that can used on the client side to collect user-input would REALLY boost my productivity!!   It would also make field-names line up perfectly in the JSON between client and server!!

**Comment by medz** [comment]
In the new version (v4), I abandoned any JSON serialization tool and in the meantime I developed a tool like zod 👉 https://pub.dev/packages/ovo After the first v4 version is released, I will Start developing this feature. As a follow-up, I will create a separate PR to complete it at that time, which contains:

1. Validity verification of Input types
2. Efficient serialization of Types
3. Action supports direct incoming JSON automatic verification

Of course, in the early stage of the v4 version, all types have been roughly distributed to the `types.dart` file, which can be distributed to the front end for use.

Then the specific engine implementation of the backend is generated into the `client.dart` file.

The v4 version will be available to you soon🎉 read more #290

**Comment by medz** [comment]
@blopker @dgaedcke In the current versions `4.x` and `5.x`, the models and client code are separated in different files. And it includes `fromJson` and `toJson`.

I generated the code into separate directories in my Dart frontend and backend and exported it with a new package. It seems to satisfy the current use case.
