### ISSUE TITLE
Question: Does prisma-dart use connection pooling?

### ISSUE THREAD

**Issue by craiglabenz** [medz/prisma-dart#180]
Connection pools are an important best practice for Postgres and most databases. Does this `prisma-dart` use them? If so, I'd love to help potentially update the documentation to indicate this.

**Comment by medz** [comment]
https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/connection-pool

Yes, we use the Prisma engine, so the connection to Chiyu is consistent with Prisma.
