### ISSUE TITLE
Prisma does not support raw queries？

### ISSUE THREAD

**Issue by bigedev** [medz/prisma-dart#188]
"Prisma does not support raw queries. I've tried both MySQL and SQLite. When I used the example query in your documentation, which is 
`final result = await prisma.$queryRaw('SELECT * FROM "User"')`, 
I couldn't get any results even though there were data in the database. However, when I used 
`'final users = await prisma.user.findMany()'`,
 I was able to retrieve the data. Is there a bug in your pure SQL queries?"

**Comment by hyperonetech** [comment]
We running flutter app in windows with Xampp MySQL. When we try to run prisma.$queryRaw('select now()') or any other raw query.it always return null. How to enable raw query?
