### ISSUE TITLE
StringFieldRefInput

### ISSUE THREAD

**Issue by gaetschwartz** [medz/prisma-dart#247]
Generated classes now are generated with 

```dart
  final StringFieldRefInput? lt;

  final StringFieldRefInput? lte;

  final StringFieldRefInput? gt;

  final StringFieldRefInput? gte;
```

but `StringFieldRefInput` doesn't seem to resolve to any object. Am I missing something here ?

**Comment by medz** [comment]
Sorry, this was caused by a breaking change in Prisma 5, and it is recommended that you switch back to Prisma 4.x versions. I'm trying to finish what I'm doing and adapt to the new Prisma 5 protocol. Thanks for your feedback.

**Comment by medz** [comment]
Good news, in v4, it’s supported! Please pay attention to #290, this issue will be closed after official release
