### ISSUE TITLE
How to create data & Connecting Relation Model? I'm Confused

### ISSUE THREAD

**Issue by yusriltakeuchi** [medz/prisma-dart#255]
Hi, i'm really frustating using this package when doing create data using relations. I have 2 questions for you.

Question 1:
I have a json request like this:

```json
{
    "email": "testing@gmail.com",
    "phone": "083872130322",
    "password": "12345678",
    "profile": {
        "name": "Testing Account",
        "born_date": "1999-06-26"
    }
}
```

And in my dart code, i call create method like this:
```dart
final user = _client.prisma.user.create(
        data: UserCreateInput(
          email: data['email'] as String,
          phone: data['phone'] as String,
          password: data['password'] as String,
          profile: ProfileCreateNestedOneWithoutUserInput.fromJson(
            data['profile'] as Map<String, dynamic>
          )
        )
      );
```

The result is that the data from the User is successfully created, but the data for the Profile is not created in the database.

================================

Question 2:
How to call data User and also with any relation in a single json ?
Example:
{
   "id": 1,
   "email": "testing@gmail.com",
   "profile": {
     "name": "Testing Account"
   }
}
When using ORM, my expectation should be that the query can be called as follows:
```dart
final user = await _client.prisma.user.findUnique(
   where: UserWhereUniqueInput(email: email),
 );
return user.profile();
```
but the fact is i can't.
I can call the relation using UserFluent, but i need more effort to create a resource class to reorganize the response like this:
```dart
  static Future<Map<String, dynamic>> parse(UserFluent<User?>? user) async {
    final userdata = await user;
    return {
      'id': userdata?.id,
      'email': userdata?.email,
      'phone': userdata?.phone,
      'profile': await user?.profile(),
    };
  }
```

=======================
This is my schema if you want to check
```prisma
model User {
  id        Int      @id @default(autoincrement())
  email     String   @unique
  phone     String   @unique
  password  String
  balance   Int      @default(0)
  created_at DateTime @default(now())
  updated_at DateTime @updatedAt
  profile   Profile?
}

model Profile {
  id        Int     @id @default(autoincrement())
  name      String
  born_date  String
  user      User    @relation(fields: [user_id], references: [id])
  user_id    Int     @unique
}
```

**Comment by yusriltakeuchi** [comment]
Can you help me answer this question? Because my problem is not found in prisma.pub documentaions

**Comment by samerkh** [comment]
i think what we are looking for is `include` property. This code is from prisma client docs
```
// Return user, and posts, and categories
  const returnUser = await prisma.user.findUnique({
    where: {
      id: user.id,
    },
    include: {
      posts: {
        include: {
          categories: true,
        },
      },
    },
  })
```
however, this property does not exist in the flutter package. I hope someone responds to this because i feel like they are forgetting about this repo.

**Comment by medz** [comment]
Requires Union Types support, but Dart does not currently support it, relations currently use the fluent API

**Comment by medz** [comment]
Good news, in v4, it’s supported! Please pay attention to #290, this issue will be closed after official release

**Comment by medz** [comment]
v4 alpha version publish 👉 https://github.com/medz/prisma-dart/releases/tag/v4.0.0-alpha.0

In version v4 we support this feature
