### ISSUE TITLE
type 'Null' is not a subtype of type 'bool' in type cast

### ISSUE THREAD

**Issue by kidusdev** [medz/prisma-dart#273]
I Am using dart 3.1.3 and flutter 3.13.6 and when i run npx prisma generate it is terminating with an error
- Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Error: 
type 'Null' is not a subtype of type 'bool' in type cast

**Comment by AndryHTC** [comment]
@kidusdev duplicate of https://github.com/odroe/prisma-dart/issues/259
