### ISSUE TITLE
Another "Error: Null check operator used on a null value" case

### ISSUE THREAD

**Issue by kyugao** [medz/prisma-dart#288]
This error appears just same as #208. But the solution in that post didn't work for me. Here is my environment info, thx for the help.

- Computer And OS: Mac Sonoma 14.2 
- Dart version: Dart SDK version: 3.3.0-27.0.dev
- Prisma info: 
![image](https://github.com/medz/prisma-dart/assets/1071977/31e32a6c-2207-4df1-8eee-21575e73b6ac)
- Schema
![image](https://github.com/medz/prisma-dart/assets/1071977/36e699a2-7da4-4a98-9652-3d0f48355e5c)
- Error Message
![image](https://github.com/medz/prisma-dart/assets/1071977/02186c2c-1b00-4def-9e52-101257553a24)

**Comment by ducphan1311** [comment]
same

**Comment by kyugao** [comment]
Here is another try, I defined two client, one for dart, and one for JS
just like this
```
generator clientDart {
  provider = "dart run orm"
  output = "./dart/client"
}
generator clientJS {
  // provider = "dart run orm"
  provider = "prisma-client-js"
  output = "./js/client"
}
```
![image](https://github.com/medz/prisma-dart/assets/1071977/76d87c19-e8c3-4455-8c56-4e44bb03bc02)

the JS client generated successfully.

**Comment by ducphan1311** [comment]
> Here is another try, I defined two clients, one for dart, and one for JS just like this
> 
> ```
> generator clientDart {
>   provider = "dart run orm"
>   output = "./dart/client"
> }
> generator clientJS {
>   // provider = "dart run orm"
>   provider = "prisma-client-js"
>   output = "./js/client"
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/1071977/283041392-76d87c19-e8c3-4455-8c56-4e44bb03bc02.png)
> 
> the JS client generated successfully.

but dart client not generate. 
In the example, I also don't see the dart folder being generated: https://github1s.com/medz/prisma-dart/blob/HEAD/prisma/schema.prisma

**Comment by kyugao** [comment]
After downgrade Prisma and Prisma Client to version 4.16.2
![image](https://github.com/medz/prisma-dart/assets/1071977/ec2fb3e5-e82a-4a18-a9d5-f33c2fb8a3ef)

the dart client and generated.
![image](https://github.com/medz/prisma-dart/assets/1071977/6777a875-75bd-42ab-a0a1-057118a70e32)

**Comment by kyugao** [comment]
I tried a few history versions of prisma, and client, with my same code and environment, this issue can be reproduce start from 5.0.0.

**Comment by medz** [comment]
Please fix the version to 4.x, I am developing a new client that is compatible with 5.x because Prisma 5.x has changed the protocol,

**Comment by kyugao** [comment]
thx, I am using version 4.16.2. 
fyi @ducphan1311

**Comment by medz** [comment]
v3.4.5 version published, fixed the bug.

**Comment by medz** [comment]
And v4.0.0-alpha.0 version published
