### ISSUE TITLE
Unable to connect with sqlite

### ISSUE THREAD

**Issue by ghost** [medz/prisma-dart#311]
`[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: ClientException with SocketException: The remote computer refused the network connection.

 (OS Error: The remote computer refused the network connection.

, errno = 1225), address = 127.0.0.1, port = 5636, uri=http://127.0.0.1:5578/status
#0      IOClient.send (package:http/src/io_client.dart:122:7)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93:32)
<asynchronous suspension>
#2      _withClient (package:http/http.dart:166:12)
<asynchronous suspension>
#3      BinaryEngine._createEngineStatusValidator.<anonymous closure> (package:orm/binary_engine.dart:274:24)
<asynchronous suspension>
#4      _InternalRetry.call (package:orm/universal_engine.dart:298:12)
<asynchronous suspension>
#5      RetryOptions.retry (package:retry/retry.dart:131:16)
<asynchronous suspension>
#6      BinaryEngine._createProcess (package:orm/binary_engine.dart:198:9)
<asynchronous suspension>
#7      BinaryEngine.start (package:orm/binary_engine.dart:154:17)
<asynchronous suspension>
#8      UniversalEngine.request (package:orm/universal_engine.dart:59:5)
<asynchronous suspension>
#9      ModelDelegate._execute (package:orm/src/client/model_delegate.dart:40:20)
<asynchronous suspension>
#10     PrismaFluent.queryBuilder.<anonymous closure> (package:orm/src/client/prisma_fluent.dart:37:22)
<asynchronous suspension>
#11     PostsModelDelegateExtension.findMany.<anonymous closure> (package:test_app/src/generated/prisma/prisma_client.dart:2654:31)
<asynchronous suspension>
#12     main (package:test_app/main.dart:8:19)
<asynchronous suspension>`

**Comment by medz** [comment]
Currently, Prisma Dart does not support use in Flutter and is waiting for Prisma’s official C ABI engine.
<img width="428" alt="image" src="https://github.com/medz/prisma-dart/assets/5564821/7a6c491b-28c4-4523-af1a-8a154c423cc3">

**Comment by medz** [comment]
#328
