### ISSUE TITLE
4.x - docs, Need help!

### ISSUE THREAD

**Issue by medz** [medz/prisma-dart#313]
Please wait, the document is being written. But since my time is limited, I hope someone can compile the documentation.

I still have a ton of commercial projects to finish, and version 4.x is currently just short of raw queries.

## 2024-01-11 Updates

1. Support RAW query

**Comment by ofceab** [comment]
@medz Can't migrate my code to 4.0.0-alpha.2, I got `no element` as error after ran the generate command of prisma

**Comment by medz** [comment]
@ofceab Can you give me a simple example? I'll start fixing it

**Comment by ofceab** [comment]
@medz  Here is my example.

I use prisma for one my backend written in `dart` and using `mysql` as database.

**Example Pubspec.yam**
`name: api_server
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  crypto: ^3.0.3
  dart_geohash: ^2.0.2
  dart_jsonwebtoken: ^2.12.1
  dartz: ^0.10.1
  dotenv: ^4.2.0
  firedart: ^0.9.7
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  get_it: ^7.6.0
  http: ^1.1.2
  injectable: ^2.1.2
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  mockito: ^5.4.3
  orm: ^4.0.0-alpha.2
  shelf_cors_headers: ^0.1.5
  uuid: ^4.3.1
  shelf_router: ^1.1.4
  dart_frog: ^1.0.1
  dart_frog_auth: ^1.1.0
  dart_frog_web_socket: ^1.0.0

dev_dependencies:
  build_runner: ^2.3.3
  injectable_generator: ^2.1.6
  json_serializable: ^6.7.1
  mocktail: ^1.0.1
  shelf_router_generator: ^1.1.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
  


scripts: 
  gen-build: "dart run build_runner build"
  gen-watch: "dart run build_runner watch"
  gen-prisma: "npx prisma db push && npx prisma generate && dart run build_runner build"
  gen-prisma-2: "npx prisma generate && dart run build_runner build"
  build-docker: "dart_frog build && docker build -t ."
  `

**package.json**
`{
  "dependencies": {
    "@prisma/client": "^5.7.1",
    "prisma": "^5.7.1"
  },

  "name": "api_server",
  "version": "1.0.0",
  "main": "index.js",
  "directories": {
    "lib": "lib",
    "test": "test"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
`

Prisma schema configuration in use here is from the [annoucement page](https://github.com/medz/prisma-dart/discussions/292)

**schema.prisma providers**
`generator DartClient {
  provider = "dart run orm:client"
}

generator CopyQueryEngine {
  provider = "dart run orm:binary"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}`

After ran `npx prisma generate`. I got this :

![image](https://github.com/medz/prisma-dart/assets/65366889/79cdb15a-ae0f-411a-afb0-506ea33fdc7e)

**Comment by medz** [comment]
@ofceab generator provider set to "dart  run orm"

**Comment by ofceab** [comment]
@medz  All providers ?

**Comment by ofceab** [comment]
If so I got this after made these changes on DartClient and CopyQueryEngine
![image](https://github.com/medz/prisma-dart/assets/65366889/c05ee6ea-8595-46c2-9f19-8f8ed48b1eae)

**Comment by medz** [comment]
@ofceab No, Only one generator:

```prisma
generator client {
  provider = "dart run orm"
  output   = "dart"
}
```

**Comment by ofceab** [comment]
@medz  I just came to make these changes. I got the same error 
![image](https://github.com/medz/prisma-dart/assets/65366889/d4725db5-0eff-46d1-9970-0c20e42f6949)
