### ISSUE TITLE
Operation not permitted in MacOS Sonoma

### ISSUE THREAD

**Issue by Gopikrishna19** [medz/prisma-dart#326]
I was able to run the application just fine with Windows, but when I switched to a MacBook Pro, the project stopped working with following error:

```dart
Unhandled Exception: ProcessException: Operation not permitted
  Command: /Users/<user>/Developer/<project>/node_modules/prisma/query-engine-darwin-arm64 --enable-raw-queries --enable-metrics --enable-open-telemetry --port 63316 --host 127.0.0.1 --engine-protocol graphql
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:402:33)
#1      Process.start (dart:io-patch/process_patch.dart:38:20)
#2      BinaryEngine._createProcess (package:orm/binary_engine.dart:187:35)
#3      BinaryEngine.start (package:orm/binary_engine.dart:155:23)
#4      UniversalEngine.request (package:orm/universal_engine.dart:59:11)
#5      ModelDelegate._execute (package:orm/src/client/model_delegate.dart:40:34)
#6      ModelDelegate.$query (package:orm/src/client/model_delegate.dart:29:7)
#7      UserModelDelegateExtension.findFirst.<anonymous closure> (package:wishlez/prisma/prisma_client.dart:14285:26)
#8      PrismaFluent.queryBuilder.<anonymous closure> (package:orm/src/client/prisma_fluent.dart:37:33)
#9      UserModelDelegateExtension.findFirst (package:wishlez/prisma/prisma_client.dart:14294:25)
#10     UserController.signInUser (package:wishlez/controllers/user_controller.dart:75:36)
#11     WUserForm._signIn.<anonymous closure> (package:wishlez/components/user_form.dart:55:32)
#12     WUserForm._finalize (package:wishlez/components/user_form.dart:40:18)
#13     WUserForm._signIn (package:wishlez/components/user_form.dart:55:5)
#14     _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1183:21)
#15     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:275:24)
#16     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:652:11)
#17     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:309:5)
#18     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:242:7)
#19     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:630:9)
#20     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
#21     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
#22     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
#23     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
#24     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
#25     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:488:19)
#26     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:468:22)
#27     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:439:11)
#28     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:413:7)
#29     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:376:5)
#30     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:323:7)
#31     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:292:9)
#32     _invoke1 (dart:ui/hooks.dart:328:13)
#33     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:410:7)
#34     _dispatchPointerDataPacket (dart:ui/hooks.dart:262:31)
```

Mac hardware: Apple M3 Pro
MacOS version: Sonoma 14.1 (23B2073)
Node: 20.11.0
NPM: 10.2.4
ORM: 3.4.6

Please help.

**Comment by Gopikrishna19** [comment]
I am able to run the binary in question directly though, withou any problem. I also check the permissions...

```bash
❯ ls -al node_modules/prisma
-rwxr-xr-x   1 gopi  staff  17516080 Jan 24 10:28 query-engine-darwin-arm64
```

```bash
❯ ./node_modules/prisma/query-engine-darwin-arm64 
{"is_panic":false,"message":"Datamodel should be provided either as path or base64-encoded string.","backtrace":"   0: __mh_execute_header\n   1: __mh_execute_header\n   2: __mh_execute_header\n   3: __mh_execute_header\n   4: __mh_execute_header\n   5: __mh_execute_header\n   6: __mh_execute_header\n"}
```

**Comment by medz** [comment]
If you launch from `/Users/<user>/Developer/<project>`, there are two possible motivations for this:

1. Due to macOS, the current user needs to be authorized to access the `/Users/<user>/Developer/` directory. There is no problem if you access this path from the console, because this directory was created by the user. But the dart process doesn't seem to be able to access that path.
2. You may try the `chmox +x /Users/<user>/Developer/<project>/node_modules/prisma/query-engine-darwin-arm64` command to see if it can fix the problem.

I speculate that the reason is 2. You can try to use the 2 command to increase the execution permissions of all users, because the binary engine can detect that the file may have access permissions through the `/Users/<user>/Developer/<project>` directory. , but does not have execution permissions.

Of course, your issue feedback is meaningful. It reported two questions:

1. How to solve common problems.
2. Potential problems that may result from using absolute paths for engine paths instead of paths relative to `pwd`.

I will release a new version that will resolve the path to a path relative to `pwd` to execute the binary.

Thank you very much @Gopikrishna19 for your detailed feedback.

**Comment by medz** [comment]
@Gopikrishna19 
If you upgrade to `3.4.8` or `4.0.0.beta-2` version, this problem should not occur.

If the problem persists, you can try `chmod +x` to increase permissions. If the problem still cannot be fixed. You may need to try more or debug.

My devices: `Apple M1`/`Windows 11`/`Linux any` have been tested and there is no such problem.

**Comment by Gopikrishna19** [comment]
Thanks for the suggestions, and I apologize for the delayed reply. Just now got to catch up on my project.

I already tried the `chmod +x`. That is where I got the `ls` response from. You may notice it has `x` permission by default (from `prisma generate`) and I didn't have to do anything.

I am back on my Windows machine for now, I shall try the newer version this everning and let you know,
