### ISSUE TITLE
Generated models have optional properties when defined as required in schema

### ISSUE THREAD

**Issue by devklick** [medz/prisma-dart#336]
In my `schema.prisma` I have a model defined with what I understand to be a required field, since it's not using the [optional modifier](https://www.prisma.io/docs/orm/prisma-schema/data-model/models#optional-and-mandatory-fields):
```prisma
model Person {
  id   Int    @id @default(autoincrement())
  name String @db.VarChar(60)
}
```
I've run the generator as per [the docs](https://prisma.pub/getting-started/setup.html#generating), with:
```
npx prisma generate
```
But the generated Person class has both the `id` and `name` properties as being optional:

```dart
class Person {
  const Person({
    this.id,
    this.name,
  });

  factory Person.fromJson(Map json) => Game(
        id: json['id'],
        name: json['name'],
      );

  final int? id;

  final String? name;
}
```

Is this the intended behaviour or have I missed something? 

Using version 4.0.0-beta.3

**Comment by medz** [comment]
This is the expected behavior. All fields of model are optional fields. The main purpose is for me to adapt the select and include functions (for selecting only some fields or additional fields containing relationships)

**Comment by devklick** [comment]
@medz Thank you for clarifying. 

Since this appears to be different behaviour to Prisma JS, it might be worth adding something in the [model docs](https://prisma.pub/getting-started/schema.html#model). 

I'll close this issue as you've confirmed it's expected behaviour

**Comment by medz** [comment]
@devklick 

> Since this appears to be different behaviour to Prisma JS

Yes, since Prisma JS/TS relies on TS's type calculation, types can be constructed dynamically. Other languages do not have support for this feature. If you want to implement select/include, you can only use nullable types.

**Comment by AndryHTC** [comment]
@medz are you planning to do a Dart specific fix for this case?

Having ALL nullable types means no null safety and no null safety means ultimately no type safety, that is the major reason to use an ORM tbh.

**Comment by medz** [comment]
@AndryHTC I don't know if I should do this. In TS, using select can use type calculation to get safe types.

But Dart is the only one that is not possible, and most other compiled languages ​​are not. In order to support the select function, I chose to generate all models as nullable.

In actual use, it does require developers to fully know what columns they select and use the `!` symbol to make it correct.

But the reality is that most people will not use the select function, and the type of the model should be consistent with the schema.

So I have a plan to optionally remove the select function in future versions, and then extract the include function. To ensure that the model class and schema def are consistent.

**Comment by medz** [comment]
Actually, I have another crazy idea, but it will not appear in `prisma-dart`, which is to design a set of query methods that conform to Dart. I have tried many things in the `oh` package before, but I didn't find a better way than prisma CRUD APIs.

I will continue to try when I am not busy in the future. The oh package will be built on top of `prisma-dart` and provide APIs different from Prisma Client.

> All this is still in the experimental stage

**Comment by AndryHTC** [comment]
What about something like this?

```
class Attribute<T> {
  final T _value;

  Attribute._(this._value);

  factory Attribute.fromJson(dynamic json) {
    if (json == null) {
      throw ArgumentError('Cannot instantiate Attribute with null value');
    }
    return Attribute._(json as T);
  }

  T get value => _value;
}
```

So in the Dart model you can still make all the attributes nullable, but if they are included in the select, we can use their original type and nullability

Example:
```
// jsonData has all the attributes
final model = Model.fromJson(jsonData);

// Safe access to the uuid value
print(model.uuid!.value);  // This is guaranteed to be a non-null String
print(model.nullableField!.value);  // This is nullable String
```

**Comment by AndryHTC** [comment]
@medz
