### ISSUE TITLE
Flutter Integration Example app throwing build error

### ISSUE THREAD

**Issue by kidusdev** [medz/prisma-dart#385]
`bash
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':orm_flutter:buildCMakeDebug[arm64-v8a]'.
> com.android.ide.common.process.ProcessException: ninja: Entering directory `C:\Users\Kidus\AppData\Local\Pub\Cache\hosted\pub.dev\orm_flutter-0.0.5\android\.cxx\Debug\33173563\arm64-v8a'

  C++ build system [build] failed while executing:
      @echo off
      "C:\\Users\\Kidus\\AppData\\Local\\Android\\Sdk\\cmake\\3.18.1\\bin\\ninja.exe" ^
        -C ^
        "C:\\Users\\Kidus\\AppData\\Local\\Pub\\Cache\\hosted\\pub.dev\\orm_flutter-0.0.5\\android\\.cxx\\Debug\\33173563\\arm64-v8a" ^
        orm_flutter
    from C:\Users\Kidus\AppData\Local\Pub\Cache\hosted\pub.dev\orm_flutter-0.0.5\android
  ninja: error: '../../../../query_engine/arm64-v8a/libquery_engine.a', needed by 'C:/Users/Kidus/Downloads/medz prisma-dart main examples-flutter_with_orm/build/orm_flutter/intermediates/cxx/Debug/33173563/obj/arm64-v8a/liborm_flutter.so', missing and no known rule to make it

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 20s
Error: Gradle task assembleDebug failed with exit code 1

Exited (1).

`

**Comment by medz** [comment]
@kidusdev Fixed package `orm_flutter` in `v0.0.6` version

**Comment by kidusdev** [comment]
I will try it and give you feedback ... thanks for the fast response and fix @medz
