### ISSUE TITLE
SocketException: Connection refused (OS Error: Connection refused, errno = 111)

### ISSUE THREAD

**Issue by mcquenji** [medz/prisma-dart#437]
### What version of Prisma Dart is running?

5.2.0

### What version of Prisma CLI is running?

5.21.0

### What type of app are you using?

Dart Native (Server/CLI)

### What database are you using?

PostgreSQL

### What steps can reproduce the bug?

Setup a basic shelf_modular server. Then try to access the database once a route is called. The entire codebase producing the error can be found [here](https://github.com/necodeIT/license_server). 

### What is the expected behavior?

The database is queried correctly and results are returned.

### What do you see instead?

ERROR - 2024-10-16 17:24:08.947090
GET /admin/licenses/123
Error thrown by handler.
SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = 127.0.0.1, port = 45628
dart:_http                                        _HttpClient.openUrl
package:webfetch/src/client/client.io.dart 22:23  Client.send
client.io.dart:22
package:webfetch/src/fetch.dart 63:24             fetch
fetch.dart:63
package:orm/src/engines/binary_engine.dart 62:28  BinaryEngine.request

### Additional information

Love the package ❤️

**Comment by medz** [comment]
@mcquenji We are investigating, please wait. I will comment on this issue if there is any progress. ❤️

**Comment by medz** [comment]
@mcquenji https://github.com/necodeIT/license_server/blob/main/bin/main.dart#L55

I noticed that you shut down the engine in main. This approach is suitable for disposable apps (such as CLI), for web you should shut it down in the logic that confirms your web server exits.

Or you don't need to shut down the database query engine (it just has a certain probability that the chind process will not be shut down after the Dart process exits unexpectedly)

**Comment by medz** [comment]
Maybe I should update the documentation to tell developers that this method of ensuring the query engine is shut down is not applicable to Web Server applications.

**Comment by mcquenji** [comment]
oh god, now i feel stupid 😓 But thanks for your help ❤️
