### ISSUE TITLE
feat: Support middleware

### ISSUE THREAD

**Issue by medz** [medz/prisma-dart#44]
ref https://www.prisma.io/docs/concepts/components/prisma-client/middleware

**Comment by medz** [comment]
Hope it will be added in the next version

**Comment by melWiss** [comment]
any news on this?

**Comment by medz** [comment]
@melWiss

**Comment by medz** [comment]
@melWiss Although Prisma officially supports middleware, it is outdated. The for dart client is as consistent as possible with the Prisma official client.
