### ISSUE TITLE
TypeError: 'MappedListIterable<dynamic, dynamic>' is not a subtype of 'Map<dynamic, dynamic>' when using $raw.query

### ISSUE THREAD

**Issue by renanpk** [medz/prisma-dart#450]
### What version of Prisma Dart is running?

5.2.1

### What version of Prisma CLI is running?

5.22.0

### What type of app are you using?

Dart Native (Server/CLI)

### What database are you using?

PostgreSQL

### What steps can reproduce the bug?

Use the $raw.query method with any valid SQL query.
Observe the runtime error.

### What is the expected behavior?

Instead of returning a list of maps, the method produces a MappedListIterable, leading to the following runtime error:
Type 'MappedListIterable<dynamic, dynamic>' is not a subtype of type 'Map<dynamic, dynamic>'

### Additional information

print on query method:
results[JsonQueryAction.queryRaw.name]: ({item_id: {prisma__type: int, prisma__value: 0}, price: {prisma__type: int, prisma__value: 1}, total_quantity: {prisma__type: bigint, prisma__value: 25}})
type: MappedListIterable<dynamic, dynamic>

No additional details are available at this time. If the return type of $raw.query is not meant to be directly processed as a Map, documentation or examples of the correct usage would be helpful.

**Comment by medz** [comment]
<img width="846" alt="image" src="https://github.com/user-attachments/assets/6bed76d6-deca-4c02-a530-e226cd2519c4">
`$raw.query()` explicitly returns a List<Map<String, Object?>> type, which seems inconsistent with the error you reported.

**Comment by medz** [comment]
@renanpk I think I found your problem. Did you upgrade to Prisma CLI 5.22 and then run prisma generate command? I checked your extra information and found that the results structure is returned by a very old Prisma engine.
