### ISSUE TITLE
Not being able to generate enums

### ISSUE THREAD

**Issue by SunP04** [medz/prisma-dart#458]
### What version of Prisma Dart is running?

3.4.8

### What version of Prisma CLI is running?

6.0.1

### What type of app are you using?

Dart Native (Server/CLI)

### What database are you using?

PostgreSQL

### What steps can reproduce the bug?

Create an enum, then create a model that depends on that enum.

Example:

```prisma
model Reminder {
  id          String        @id @default(uuid())
  title       String
  description String        @default("")
  state       ReminderState @default(OPEN)
  remindAt    DateTime
}

enum ReminderState {
  OPEN
  COMPLETED
  CANCELED
}
```

### What is the expected behavior?

The enum should be created before the model.

Correct order: ReminderState -> Reminder

### What do you see instead?

It compiles orm and prisma correctly, but since probably the engine is trying to create the model first, then enums, it crashes when trying to find the given enum.

![image](https://github.com/user-attachments/assets/4c12241a-e8ca-4d06-b0ef-11dda961a9c2)

**Error:** **`Enum createmanyreminderandreturnoutputtypescalarfieldenum not found`**

### Additional information

This was on a cleanly started application (only did `prisma init` then `prisma generate`).

Project for Example: https://gitlab.com/SunP04/reminder-api/-/tree/prisma (prisma branch)

Full Information of prisma versioning
![image](https://github.com/user-attachments/assets/90cc5804-94b4-4293-b35d-7aba0f1faa9b)

**Comment by SunP04** [comment]
Error source: https://github.com/medz/prisma-dart/blob/main/packages/orm/bin/src/generate_enum.dart#L84
Called in: https://github.com/medz/prisma-dart/blob/main/packages/orm/bin/src/generate_enum.dart#27

It seems to be called during it's being generated, so the `dmmf.TypeNamespace` just doesn't seem to know it exists yet, but I might be very wrong on that one.

**Comment by medz** [comment]
OK, I will check it later today.

**Comment by medz** [comment]
@SunP04 You can update the orm version in your pubspec.yaml to version 5.2.1 to solve the problem. I don't know why, it seems that the dart pub add orm command will install the older version. Manually updating the version number can solve the problem.

**Comment by medz** [comment]
5.2.1 is the latest version on pub.dev. I seem to have encountered this situation in other software. Maybe it's a problem with pub cli.
