### ISSUE TITLE
2 examples in the documentation missing from master

### ISSUE THREAD

**Issue by kdo1234** [medz/prisma-dart#83]
2 of the 3 examples referenced in the documentation are missing from master. 
Rest API (with shelf) - Example of a Rest API with Prisma ORM for Dart and shelf
Flutter (Using Data Proxy) - Example of a Flutter app using Prisma ORM for Dart and Data Proxy

They are not here: https://github.com/odroe/prisma-dart/tree/main/example/rest_api

Do the examples exist anywhere? If so I can probably fix the documentation.

Thank you

**Comment by medz** [comment]
@kdo1234 RESTful API example added it.

**Comment by anton-vidext** [comment]
Is there an example for Flutter (Using Data Proxy)?

**Comment by medz** [comment]
> Is there an example for Flutter (Using Data Proxy)?

@anton-vidext I'll add it later, I'm too busy with a lot of tasks. Sometimes I forget. thanks for your reminder.
